# Generated by Django 3.0.8 on 2020-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('User_Name', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
