# Generated by Django 3.0.8 on 2020-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0002_actor_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroine_Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=50)),
                ('h_age', models.IntegerField()),
                ('h_email', models.EmailField(max_length=254)),
                ('h_pass', models.CharField(max_length=100)),
                ('h_manager_name', models.CharField(max_length=100)),
            ],
        ),
    ]
