# Generated by Django 3.0.8 on 2020-07-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0003_heroine_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_mobile', models.IntegerField(max_length=10)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('c_comp', models.CharField(max_length=100)),
            ],
        ),
    ]
