# Generated by Django 3.0.8 on 2020-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0004_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedy_Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('com_age', models.IntegerField()),
                ('com_email', models.EmailField(max_length=254)),
                ('com_nof_movies', models.IntegerField()),
                ('com_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('com_lang', models.CharField(choices=[('TELUGU', 'TELUGU'), ('HINDI', 'HINDI'), ('TAMIL', 'TAMIL')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='c_mobile',
            field=models.IntegerField(),
        ),
    ]
